server: # Serveur Tomcat embarqueé
  port: 8787

spring:
  mvc: # Modele Vue Controle
    view: # pour préciser où se trouvent les jsp pour la Vue (affichage coté client)
      prefix: /
      suffix: .jsp
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
     url: jdbc:mariadb://localhost:3306/sysco # sysco: le nom de la BDD
     username: admin # root
     password: admin # glopglop


logins:
    name: "rabbitmq"
    username: "pifou"
    password: "pasglop"

