sysco:
  servers:
    rabbitmq:
      adress: "193.48.57.166"
      port: 15672
    tomcat:
      address: "193.48.57.166"
      port: 8787

  logins:
    - name: "rabbitmq"
      username: "ima2a5-4fun"
      password: "glopglop"

  spring:
    datasource:
      url: jdbc:mariadb://localhost:3306/test
      username: user
      password: password
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true