server: # Serveur Tomcat embarqueé
  port: 8787

spring:
  mvc: # Modele Vue Controle
    view: # pour préciser où se trouvent les jsp pour la Vue (affichage coté client)
      prefix: /
      suffix: .jsp
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
     url: jdbc:mariadb://localhost:3306/sysco # sysco: le nom de la BDD
     username: admin
     password: admin


logins:
    name: "rabbitmq"
    username: "ima2a5-4fun"
    password: "glopglop"


###############################################################################
# Les trucs en bas ne marchent pas pour le moment (probleme d'indentation déja)
###############################################################################
sysco:
  servers:
    rabbitmq:
      adress: "193.48.57.166"
      port: 15672

  spring:
    message:
      basename: validation